### ISSUE TITLE
when searching on text bring up entities with partial matches

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/NERVE#11]

**Comment by ilovan** [comment]
@SusanBrown , isn't that outside the purview of NERVE? Just wondering if:

1. It wouldn't make more sense to bring up partial matches, no  matter what you search on (text or standard)
2. It wouldn't make more sense to move this to the entity lookups repo (https://github.com/cwrc/CWRC-PublicEntityDialogs);

I realize this issue was posted before the new entity lookups were implemented into CWRC-Writer or NERVE, but I think the point made is still valid and that the issue is a part of the larger epic of improving the recall and precision of the entity lookups in general.

**Comment by ilovan** [comment]
works on partial matches now with the new dialogs
